//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.12 at 09:11:58 PM AEDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:sunat:names:specification:ubl:peru:schema:xsd:SummaryDocuments-1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sunat.names.specification.ubl.peru.schema.xsd.summarydocuments_1;
